#!/bin/sh

main(){
    if [ ! -z $1 ] ; then
        local o_name=$(ls -l | awk '/^d/ {print $9}')
        local n_name=$1
        sed -i "s/$o_name/$n_name/g" ./manage.py ./$o_name/settings.py ./Procfile ./$o_name/asgi.py ./$o_name/wsgi.py
#        mv ../$o_name ../$n_name
        mv $o_name $n_name
    else
        echo "Coloque um nome"
    fi
}



main $1 
